### ISSUE TITLE
[Firefox ESR] Tab separators randomly disappear

### ISSUE THREAD

**Issue by dreamsynth** [zapSNH/zapsCoolPhotonTheme#1]
This happens more often when moving tabs. If you remove a part of the CSS that uses the "has" selector, the separators start to display correctly and stop disappearing.

**Comment by zapSNH** [comment]
See [1792501 - has selector stays frozen](https://bugzilla.mozilla.org/show_bug.cgi?id=1792501). This is a result of a tab switch and the :has selector not responding.

I can't fix it but I'll add a thing in the readme telling people to remove the has bit if they want their tab separators to show up always.

**Comment by zapSNH** [comment]
Firefox 119 has been released. Does it no longer disappear now?

**Comment by dreamsynth** [comment]
> Firefox 119 has been released. Does it no longer disappear now?

Now everything works properly, the tab separators don't disappear

**Comment by dreamsynth** [comment]
> Firefox 119 has been released. Does it no longer disappear now?

Now everything works properly, the tab separators don't disappear

**Comment by zapSNH** [comment]
I'll reopen this since Firefox ESR seems to still have this issue.
