### ISSUE TITLE
Tab names over icon

### ISSUE THREAD

**Issue by Pixel556** [zapSNH/zapsCoolPhotonTheme#2]
<img width="221" alt="Screenshot 2023-12-31 at 10 33 06 AM" src="https://github.com/zapSNH/zapsCoolPhotonTheme/assets/95143545/1e73ef3e-c704-40c3-9eda-0ce7c70fbfc2">

**Comment by zapSNH** [comment]
What version of Firefox are you on?
If you're on ESR, can you try the FF 119 version https://github.com/zapSNH/zapsCoolPhotonTheme/archive/refs/heads/119.zip

**Comment by Pixel556** [comment]
I'm on ESR, but the rolling release ESR version has the same bug.

**Comment by zapSNH** [comment]
Have you tried the absolute latest version?

**Comment by Pixel556** [comment]
Yup.

**Comment by Pixel556** [comment]
Might be useful, but I'm on macOS 14.1 Sonoma.

**Comment by zapSNH** [comment]
Unfortunately I don't have a Mac so I can't test if the theme's broken there. It seems fine on Windows and Linux.

As a last-resort, are you willing to try the [extension version](https://github.com/zapSNH/zapsCoolPhotonTheme#as-an-extension)? It requires you to disable addon signing (which is kinda unsafe) but maybe it could work.

**Comment by Pixel556** [comment]
I'll try the extension version, and I don't mind disabling addon signing cause I don't use addons that much. I'll try the extension version and if it contains that bug or not I'll post it here.

**Comment by Pixel556** [comment]
<img width="638" alt="Screenshot 2023-12-31 at 2 37 02 PM" src="https://github.com/zapSNH/zapsCoolPhotonTheme/assets/95143545/69c6b985-f7e5-4e18-b2ac-f24e08c914a1">
I think this might be the problem. I didn't enable any of those, so I'll try that too.

**Comment by zapSNH** [comment]
Oh yea those are pretty important lol

**Comment by Pixel556** [comment]
aaand that was literally the problem. Thanks for the help tho. I think `layout.css.nesting.enabled` is required to actually fix this problem.
