### ISSUE TITLE
Missing X button on tabs

### ISSUE THREAD

**Issue by iansquenet** [zapSNH/zapsCoolPhotonTheme#3]
### Describe the solution you'd like

I have been trying to figure out how to get the X button on all the tabs like it used to be before when you had many open tabs, but can't figure it out.

### Screenshots

![image](https://github.com/zapSNH/zapsCoolPhotonTheme/assets/36297463/19e2aec8-5cfc-4856-a892-542cb4310d18)

### Others

- [ ] I am able to help with the feature request.

**Comment by zapSNH** [comment]
I've added `uc.always-show-close-button`. Check the latest commit.

**Comment by iansquenet** [comment]
![image](https://github.com/zapSNH/zapsCoolPhotonTheme/assets/36297463/1c461814-5e29-4e19-9551-6c12ede0ae72)
I'm unsure if it's a bug or I messed something up, but the X button seems to be overlayed on top of the volume button when focused on another tab.

![image](https://github.com/zapSNH/zapsCoolPhotonTheme/assets/36297463/953bd55d-7570-44f6-a82c-bed39b63ac56)

**Comment by iansquenet** [comment]
Sure! It mostly happens when you have a bunch of tabs open.

https://github.com/zapSNH/zapsCoolPhotonTheme/assets/36297463/7f835d7c-6678-461f-b671-dada8d12d3f8
