### ISSUE TITLE
all navbar buttons are black on all themes

### ISSUE THREAD

**Issue by DeformedSAS** [zapSNH/zapsCoolPhotonTheme#5]
### Prerequisites

- [X] I have followed the installation guide.

### Describe the Bug

for some reason after firefox got updated i installed the latest version of the theme and now all of the icons are black..

### Expected Behavior

the icons should be white in dark mode and not black

### Steps to Reproduce

install the theme.

### Screenshots

![image](https://github.com/user-attachments/assets/a7f52020-54ec-44d0-8331-26cc354de155)

### OS

Windows 10 22h2 x64

### Browser Version

Mozilla Firefox 128.0.3

### Theme Version

Release 128

**Comment by zapSNH** [comment]
Is `svg.context-properties.content.enabled` set to true in about:config?

**Comment by DeformedSAS** [comment]
yes i did and it didn't chanfe anything

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zapSNH** [comment]
Can you try to [create a new profile](https://support.mozilla.org/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US#w_create-remove-or-rename-a-profile), install the theme, and see if the issue still occurs?

**Comment by DeformedSAS** [comment]
> Can you try to [create a new profile](https://support.mozilla.org/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US#w_create-remove-or-rename-a-profile), install the theme, and see if the issue still occurs?

that seems to have fixed the issue. thanks

**Comment by DeformedSAS** [comment]
i'll close this issue
